language: ruby
rvm:
- 2.2
- 2.1
- 2.0
- 1.9.3
- 1.9.2

script: 'bundle exec cucumber'

env:
  global:
  - secure: lXC1wP7vriKcR54He23sX15XbNvT8C52sdTvqpd8toOPBFUwcTBOjPVCLYcC2zJOSs0Oi3ymHMWDeo6Bjb2YF03Th391oYAuLQs0fk4hMgrgMqz2wihi2a6ZLvh30Daa2sdxYPh7nP/uEKC8avvcD1inrq0W12v+IZrppukwq0SOqlcMagzTdOPkSJj3IiWMbflf0OtClbW+kU9Hy1VODQrlgFuXETr4UOvguFsxD9Stuc5Tn+KZm9EfbYSugHk879rXGQYvfP4+R1UWxVi42zu6Stk8dJWXksrfSjU5EqlBqrVswgU/VLe/ww5TEldRy5tZ4y9vL2Zx8eG1rjPftXPnKu+k3liz1FSAqjFK2VwP9quPjviJ1cDXOFL0gQLA9bEaUA3wZybEt1HKiUcpGqYKfmDTbbHoN1d3U1lNoSx/EHxpfhId8y5tgVGD4pJYCTeyZU7MtL9b4aw0BVHwdLlieS7Ec2EhulRNwXQw1HuN1OQPB8eCV7ELsB6rN1iIUFRyO0sfAJRQaqed4oZkKOZSg5mjqzspcsYsnrB1B592kVJ3EsOZzrJD3qJKoMWS6xiqdXxMAlQrbj1Bowes+jls7TDKpkhyAXDaui+Up1t0xcCZ8vR8Bl6ek4P+auK6KQOOthP0gdt3OAObaTrdd+MAoVFvjT/tAqmL35t+Akc=
  - secure: WOkyQSjueGIoO9URTdsTCufuztd1uS4mTbzBGTwPSx/AgHq17pSLp/nJs5VvYJgKAihBMQApRTEXmjiCKgqrmM+u5ZJaxrEIZ/Pcpe4tu6NvRFGvcdmnxufyBvGgXVLcvCJmlXPrE954leNRm/9a03PH9PFp0ySj8KLpnR2SASwBW3VIj5VrxyjfkzRZ2n2wKoxVcPoiaXmsjPzRcrZlH6DlfNuiwD7vKEf8ecpbm1dJlAAm+W4Lbaee8H3fDZg4Lk8XMK2kHZLpdi2ZdtFX4QbgSKAhgqWK04L7FCWidhMmDm8y+Pg/SzLuMiATNhIR87ENvrnG337WdmeeZIZrkf+d97gU+oxV9Zisn7kbZ4Y8YfM5WhlJnmT5R0MQaJi8bGWWmAZqSs0uqGXpSFO4xu5ogdUdkdKqQzcDSHkxivgQqSUEQaMX1EtFCIwL6ILc2a8ezc2tP9PDLAnzz776NcBNnSUb0M1YofevADBjwcy8fmW6RUcLK/BqMOnS9c06lX6bnku3Tg9gGjZ1uz8w94s+QApOBMNTgA2HDvFWHoUIwbM4g12odlkuMg1GmHQe1o/RBCevgKu98wO6+PO2O+ZDnL0MF2aB3HI+bwtzXZ2DIauGbavE16hzb99COxVZ0erk+Pu/aiGsa2v3MANTWNB73QrzwtJFB2RvnA9HvM4=
